### ISSUE TITLE
Recommended-min-ver

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#218]
Current proposal is to just example the version label (e.g., 1.2.3) and accept any version that is logically greater. (e.g., 1.2.4, or 1.3.y, or 2.x.y).

In discussion on 28th Nov:
 - This is just a recommendation (i.e., machine readable), but aimed towards authors.  Strict conformance is due to be handled via YANG packages.
 - Main goal is to identify a new obvious dependency (e.g., the addition of a new type into ietf-yang-types.yang)
- Text needs to include clear warning about creating a import dependency on a branched history.  I.e., authors need to be careful.  E.g., could include examples in the annex to describe behaviour.

Still open:
- Do we allow a version with a modifier in recommended-min?

**Comment by xorrkaz** [comment]
Just because I do a recommend-min 2.1.0 doesn't mean there is branching.  I may be going completely linear, and 2.1.0 will become 2.2.0 will become 3.0.0.  I think in some cases it may be hard to know if branching is involved.  That said, if you're a shop that plans branching, the warning makes sense.

In terms of recommend-min and modifiers, I've come around that modifiers don't add additional complexity.  The approach much be documented that all modifiers are "pruned" for purposes of recommend-min comparison.  Only the version numbers are compared.

**Comment by rgwilton** [comment]
Matches if the version label exactly matches the label (including optional modifier), or has a higher version number (e.g., for version x.y.z).
