### ISSUE TITLE
Timestamp or date?

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-ver-dt#33]
Should a package have a timestamp or a date?

In a way, a date feels sufficient as long as it is not required to be unique - a timestamp might just be including non relevant information.

However, the YANG packages draft allows a timestamp to be associated with a document.

[Moved from rgwilton/YANG-Packages-Draft/issues/42]

**Comment by jsterne** [comment]
I've sometimes wondered about the limited granularity of a date for a YANG module (especially given the uniqueness requirements of it). It may have been better to have used date-and-time from the start for YANG modules. But given that modules just use date, and packages will churn with less frequency than modules might, we can probably live with date.

**Comment by rgwilton** [comment]
I think that packages could potentially churn more quickly than modules (e.g. it they were updated automatically as part of a build), but then I'm not proposing that revision-dates are unique for YANG packages, just a piece of metadata.

**Comment by jsterne** [comment]
Inclined to make this date-and-time on the call today. A package author may be using revision-label as the "key" and if they publish multiple versions on the same date, they may want the metadata to include the time (rather than just the same date for both versions).

No changes needed to the draft.
