### ISSUE TITLE
Defining pre-release version precedence

### ISSUE THREAD

**Issue by xorrkaz** [netmod-wg/yang-ver-dt#60]
If the MAJOR, MINOR, PATCH of a pre-release version doesn't change or jumps forward, the pre-release precedence rules are well-established based on semver.org.  However, if a module is initially going to be a MAJOR version ahead but during development it's reverted to only a MINOR version increment, the precedence rules break.  For example:

1.0.0 < 2.0.0-pre-release <broken!> 1.1.0-pre-release < 1.1.0

The above could be fixed simply by saying pre-releases don't have implied precedence and the module lineage should be used instead.   But then we lose any semantic meaning in the revision-labels.  Though, with the draft names in the pre-release strings, there is a direct link back to the draft, which has history in Data Tracker.

Another thought is to say that revision-labels can never go backwards.  That if you decide on 2.0.0 as the next string, that the final product will be 2.0.0.  This can work because it will most likely trigger authors to use the next MINOR (or even PATCH) version throughout development until the final release.  Then, and only then is a true YANG semver assigned based on the totality of the development.

Ultimately, there should be something decided and written on how to interpret pre-release version components.

**Comment by xorrkaz** [comment]
This is still a TODO item in the draft and probably deserves some more discussion.  Some other text in the draft implies that pre-release versions have no implied precedence.  Let's tee this up for an upcoming meeting.

**Comment by jwdonahue** [comment]
Version numbers should not be applied to content until it is ready for publication/release. Developers working on vNext, should inherit the previous version, bump the patch number and append a prerelease tag to it at build output/publication time. Test, rinse and repeat, until you know whether you have any breaking changes, new features, or just a bunch of bug fixes in the current change set.

Your real problem is even deeper than this however, because you haven't actually addressed branching and parallel development issues. Hence, my suggestion that SemVer might not really be what you are looking for. There are many teams out there committing SemVer strings to their repos and/or embedding them in their source code, but it just doesn't scale well.

One solution is to append a `-a.b.Dev.devname.N` tag to anything that is built on a developer's box, and `-a.b.Build.labName.hostName.branch.N` to anything built on a build server, to the last base version triple for whatever branch it's built from.

Note the first two fields of the prerelease tag? Why `a.b`?  Well that's due to the [SemVer precedence rules](https://semver.org/spec/v2.0.0.html#spec-item-11), which are lexical, not semantic. You wouldn't want your developer builds to sort higher than your `-beta.N` releases, right?

**Comment by xorrkaz** [comment]
Text has been added to rev -03 to address this.  See the "Pre-release Version Precedence" section.
